# Generated by Django 2.2.3 on 2019-07-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('solving', 'Решается'), ('solved', 'Решено')], default='solving', max_length=8),
        ),
    ]
