# Generated by Django 2.2.3 on 2019-07-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_problem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('new', 'Новое'), ('solving', 'На рассмотрении'), ('solved', 'Решено')], default='new', max_length=8),
        ),
    ]
