# Generated by Django 2.2.3 on 2019-07-21 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_problem_fixer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='fixer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixer', to=settings.AUTH_USER_MODEL),
        ),
    ]
